Il-Libro-Open-Source/book

AMBASSADORS.md, CODE_OF_CONDUCT.md, README.md
Lascio aperta questa PR per qualche giorno per raccogliere le vostre idee e feedback per questa prima versione di README e pagine associate!
=> docs: implementate le prime versioni di README + AMBASSADORS + CODE_OF_CONDUCT

notes/meeting-13-09-2023.md
1. Fixato un typo
2. Cambiato l'inizio di una frase
3. Provato ad indovinare la parola mancante 😬 
EDIT: 4. lanciato `npm run format` di cui mi ero totalmente scordato 😅
=> Fix a typo and a couple of small changes

notes/meeting-13-09-2023.md
Updated some notes related to yesterday's meeting.
=> docs: updating meeting notes

README.md
=> Fixa errore nel README.md

.commitlintrc, .lefthook/commit-msg/commitlint.sh, lefthook.yml, package-lock.json, package.json
👋🏽 
Dato che abbiamo deciso di seguire `conventional commit`, ho aggiunto la CLI in modo da controllare che ad ogni commit venga rispettata la convenzione.
=> Aggiunto conventional commit

.github/FUNDING.yml
Essendo stati approvati anche su Github, credo sia coerente e corretto aggiungere il file YAML per il funding qualora qualcuno fosse interessato.
=> Creazione FUNDING.yml

docs/index.md
@Il-Libro-Open-Source/tech-group Ho modificato l'indice, ma mi rimetto a voi per capire se basta questo o c'è altro da fare per rendere il capitolo disponibile online
=> Aggiunge all'indice il capitolo Cosa significa essere dev

LICENSE.md
Non essendo una cima sull'argomento, ho fatto una ricerca in rete ed ho trovato questa che sembra essere quella scelta dalla maggioranza.
Lascio quindi il link della fonte, e mi rimetto a chi è più esperto di me sull'argomento per il benestare o il rigetto della PR.
Fonte: https://github.com/santisoler/cc-licenses/blob/main/LICENSE-CC-BY-NC-SA
=> Aggiunta licenza del progetto

docs/testing/README.md
Ho riportato alcune mie considerazione fatta nella PR di draft, piu' una piccola descrizione del TDD, tratta da un articolo di @rafleze
=> PR a Proposta prima bozza capitolo testing

.gitignore, docs/aziende-di-consulenza-vs-prodotto/README.md, package-lock.json, package.json
Sono state scritte le prime sezioni:
- Obiettivo del capitolo
- Azienda di consulenza
- Azienda di prodotto
=> Aziende di consulenza vs prodotto - scritta sezione obiettivo capitolo, azienda di consulenza, azienda di prodotto

docs/università-vs-self-made/README.md
Ciao!
Ecco un breve accenno relativo agli ITS. Mi sono permesso di creare la cartella e la pagina dedicata all'argomento visto che mancavano sul branch. Mi rendo conto che in confronto ai paragrafi dedicati alla formazione in Università e a quelli da Autodidatta, questo andrebbe messo in fondo, però intanto lo propongo così da poter apportare modifiche in caso ce ne fosse bisogno.
Grazie
=> Aggiunge accenno ITS

.prettierrc
Vedi anche [Pull request 185](https://github.com/Il-Libro-Open-Source/book/pull/185)
=> fix: sistemazione fine riga unix anche su prettier

README.md
=> chore: aggiunto link al libro nel readme

CONTRIBUTING.md
Come indicato nella #158 ho aggiunto riferimenti ad altri IDE. Ho inserito JetBrains come famiglia oltre che Vim e un generico link alla doc di Prettier.
=> feat: aggiunti altri idee al CONTRIBUTING.md

docs/it/testing.md
Ho aggiunto una piccola descrizione su cosa è Playwright nella lista dei tool E2E
=> feat: aggiunto playwright nella lista tool e2e

.github/workflows/deploy.yml, _config.yml
=> feat: add github link to book page

docs/it/cosa-significa-essere-dev.md
=> Fix titolo nel capitolo Cosa significa essere dev

docs/it/curriculum.md
- Sistemati tutti i titoli di paragrafo
- Fixato piccolo typo
Closes #238
=> Fix stile nel capitolo Il Curriculum

docs/it/remote-working.md
Ragazzi, dopo mille ritardi sono riuscito a completare una prima bozza del capitolo sul remote working.
Si tratta appunto di una bozza con sicuramente molte possibilità di miglioramento, ma intanto la "esco fuori" così potete dirmi se siamo sulla strada giusta per questo capitolo.
=> feat: add first remote working chapter draft

_sass/custom/custom.scss, docs/it/documentazione.md
Fixa #236 e la tabella nel capitolo documentazione
=> Fix titolo e tabelle documentazione

README.md
Proposta di aggiunta testo per canale telegram
=> docs: aggiunta canale telegram

docs/it/cultura/documentazione.md, docs/it/sviluppo/refactoring.md, docs/it/sviluppo/testing.md
Dovrebbe migliorare la resa della sintassi sia nella versione web che nella versione epub.
=> Aggiunta sintassi dei blocchi di codice in markdown
